//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingOrganizer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MODBEntities : DbContext
    {
        public MODBEntities()
            : base("name=MODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<MeetingPersonels> MeetingPersonels { get; set; }
        public virtual DbSet<Meetings> Meetings { get; set; }
        public virtual DbSet<Personels> Personels { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
    }
}
