//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personels
    {
        public int ID { get; set; }
        public int PersonelRegistry { get; set; }
        public string PersonelName { get; set; }
        public string PersonelSurname { get; set; }
        public string Department { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Meetings_ID { get; set; }
    
        public virtual Meetings Meetings { get; set; }
    }
}
